### ISSUE TITLE
ListBuilder.replace(Iterable iterable) accepts dynamic Iterable

### ISSUE THREAD

**Issue by audkar** [google/built_collection.dart#190] opened 2019-08-30 10:14 UTC
Is this intentional to pass `Iterable<dynamic> iterable` or it could be reused generic `E` [here](https://github.com/google/built_collection.dart/blob/master/lib/src/list/list_builder.dart#L48) like?
```dart
void replace(Iterable<E> iterable) {...}
```

**Comment by davidmorgan** [comment] 2019-08-30 11:32
Yes; it allows you to 'cast' an `Iterable` of the wrong type.

This made more sense in Dart 1 than Dart 2. In Dart 1, this:

`[1, 2, 3]`

has type `List<dynamic>`. In Dart 2, it has type `List<int>`.

But it would be an incompatible change now, so we're stuck with it even thought `Iterable<E>` would usually be better for Dart 2.

**Comment by audkar** [comment] 2019-08-30 12:05
> But it would be an incompatible change now, so we're stuck with it 

If someone is using this method with incompatible type iterables then they are getting run time exceptions. My guess that there shouldn't be a lot of usage in real world?

Anyway problem is that my code is error prone because of this unchecked method. We had scenario where we changed code to incompatible types with expectation that compiler will show problems, but everything blew at runtime.  

This is very oversimplified example, we change `retrieveItems` to incompatible type and boom :boom: 
```dart
class Producer {
  Iterable<Item> retrieveItems() {...}
  MySafeState getState() {
    return state.update((b) => items.replace(retrieveItems()));
  }
}
```

Whole purpose we use `built_values` at this place is to ensure state types are correct, values exist and state is immutable.

Wouldn't it be reasonable to release new major `built_value`/`built_collection` version which removes all type restrictions of dart 1?

**Comment by davidmorgan** [comment] 2019-08-30 12:33
The problem is that it's currently like a cast: you can pass in an `Iterable<Object>`, and provided the actual _values_ are of the correct types, it works.

Changing it would require changing every caller that's using it as a cast instead of an assignment. (We could add a `replaceCast` method).

I tried making the change to see what broke--at the very least, `built_value` breaks. It would be a pretty major update.

It definitely makes sense to do this if/when we release a breaking change to `built_collection`. I'm not sure it's enough to warrant its own breaking release.

Thanks for filing, though. Its good to have more attention on this issue :)

**Comment by audkar** [comment] 2019-08-30 12:51
> We could add a replaceCast method

This would be appreciated :medal_sports: Still will need to manually check in PRs that noone is using `replace()`, but at least we will have convenient method in ListBuilder :)

**Comment by davidmorgan** [comment] 2019-08-30 12:56
It's the other way around, I'm afraid; `replaceCast` would be the non-strict version, to allow `cast` to become strict.

So we could add `replaceCast` as a non-breaking change, but until we land the breaking change it would be exactly the same as `replace`.

**Comment by knaeckeKami** [comment] 2019-12-18 14:41
For people using 
`implicit-dynamic: false`, the current way of using raw types is pretty inconvenient, it requires one to specify the type parameters when calling .replace() every time, adding boilerplate code.

I would welcome either a breaking change of a second replaceXXX() method with type parameters, too.

**Comment by davidmorgan** [comment] 2019-12-18 14:43
What if we changed it to take `Iterable<Object>`?

**Comment by knaeckeKami** [comment] 2019-12-18 15:15
Should get rid of the manually specified type and work, given to covariant nature of generics in Dart, and should also be a non-breaking change.

Drawback:
It would still not be type-safe.
Code like
    ListBuilder<int>().replace(["string!"]);
would still compile.

**Comment by davidmorgan** [comment] 2019-12-18 15:17
Right.

`dynamic`->`Object` should be a non-breaking change, I think--so hopefully we can just do that.

**Comment by davidmorgan** [comment] 2021-06-09 09:32
Closing in favour of https://github.com/google/built_collection.dart/issues/241

**Closed by davidmorgan** 2021-06-09 09:32 UTC
Labels: question
